export const GET_ALL_ORDER_OF_USER = "GET_ALL_ORDER_OF_USER";
export const GET_ALL_ORDER_OF_USER_SUCCESS = "GET_ALL_ORDER_OF_USER_SUCCESS";
export const GET_ALL_ORDER_OF_USER_FALSED = "GET_ALL_ORDER_OF_USER_FALSED";

export const GET_CART_OF_USER = "GET_CART_OF_USER";
export const GET_CART_OF_USER_SUCCESS = "GET_CART_OF_USER_SUCCESS";
export const GET_CART_OF_USER_FALSED = "GET_CART_OF_USER_FALSED";

export const ADD_TO_CART_OF_USER = "ADD_TO_CART_OF_USER";
export const ADD_TO_CART_OF_USER_SUCCESS = "ADD_TO_CART_OF_USER_SUCCESS";
export const ADD_TO_CART_OF_USER_FALSED = "ADD_TO_CART_OF_USER_FALSED";

export const UPDATE_CART_OF_USER = "UPDATE_CART_OF_USER";
export const UPDATE_CART_OF_USER_SUCCESS = "UPDATE_CART_OF_USER_SUCCESS";
export const UPDATE_CART_OF_USER_FALSED = "UPDATE_CART_OF_USER_FALSED";

export const UPDATE_CART_ITEM_OF_USER = "UPDATE_CART_ITEM_OF_USER";
export const UPDATE_CART_ITEM_OF_USER_SUCCESS = "UPDATE_CART_ITEM_OF_USER_SUCCESS";
export const UPDATE_CART_ITEM_OF_USER_FALSED = "UPDATE_CART_ITEM_OF_USER_FALSED";

export const DELETE_CART_OF_USER = "DELETE_CART_OF_USER";
export const DELETE_CART_OF_USER_SUCCESS = "DELETE_CART_OF_USER_SUCCESS";
export const DELETE_CART_OF_USER_FALSED = "DELETE_CART_OF_USER_FALSED";

export const DELETE_CART_ITEM_OF_USER = "DELETE_CART_ITEM_OF_USER";
export const DELETE_CART_ITEM_OF_USER_SUCCESS = "DELETE_CART_ITEM_OF_USER_SUCCESS";
export const DELETE_CART_ITEM_OF_USER_FALSED = "DELETE_CART_ITEM_OF_USER_FALSED";